### ISSUE TITLE
Cannot start the server on Windows

### ISSUE THREAD

**Issue by guest951** [online-go/online-go.com#1149]
When trying to run the server on Windows 10 by doing `yarn install` and then `npm run dev` I get the following error:

```
[14:49:16] The following tasks did not complete: default, build_styl
[14:49:16] Did you forget to signal async completion?
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on Domain instance at:
    at ChildProcess.EventEmitter.emit (domain.js:500:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'run', 'webpack-watch' ],
  domainEmitter: ChildProcess {
    _events: [Object: null prototype] { exit: [Function: spawn_webpack] },
    _eventsCount: 1,
    _maxListeners: undefined,
    _closesNeeded: 1,
    _closesGot: 0,
    connected: false,
    signalCode: null,
    exitCode: -4058,
    killed: false,
    spawnfile: 'npm',
    _handle: null,
    spawnargs: [ 'npm', 'run', 'webpack-watch' ],
    pid: undefined,
    stdin: null,
    stdout: null,
    stderr: null,
    stdio: [ null, null, null ],
    [Symbol(kCapture)]: false
  },
  domainThrown: false
}
Program gulp.cmd  exited with code 1

Starting child process with 'gulp.cmd '
```

I found on stackoverflow that the problem can be solved by adding the option `shell: true` in the `spawn` command in `Gulpfile.js`:
`let webpack = spawn('npm', ['run', 'webpack-watch'], { stdio: 'inherit', shell: true })`

**Comment by anoek** [comment]
```I found on stackoverflow that the problem can be solved by adding the option shell: true in the spawn command in Gulpfile.js:```

Awesome, try that out and if it works, submit a PR! And thanks!

**Comment by guest951** [comment]
OK, this is the stakoverflow link where I found the solution:
https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js/39682805#39682805
