### ISSUE TITLE
Blank tournament page

### ISSUE THREAD

**Issue by gezabohus** [online-go/online-go.com#1713]
Link to the 3rd International Mandelbrot Tournament leads to a blank page. It's been like this for a day or two. Link: https://online-go.com/tournament/85113

**Comment by anoek** [comment]
Can you provide a link to the tournament please?

**Comment by gezabohus** [comment]
Sorry, there now.

**Comment by BHydden** [comment]
> There is a flash of what appears to be the correct page, but it is replaced with the blank page within a second.

I see the same thing, these are the console errors I get.

![image](https://user-images.githubusercontent.com/28991649/154766376-9035e20d-4b6d-46e3-95fa-a99de775db8d.png)


```
Uncaught TypeError: Cannot read properties of undefined (reading 'notes')
    at wm (ogs.5.1-4075-g87407d2b-8c5b6ad03f2844c9c4785ce85007af68.js:2:770638)
    at Array.sort (<anonymous>)
    at ogs.5.1-4075-g87407d2b-8c5b6ad03f2844c9c4785ce85007af68.js:2:810306
    at Array.map (<anonymous>)
    at km.render (ogs.5.1-4075-g87407d2b-8c5b6ad03f2844c9c4785ce85007af68.js:2:810270)
    at es (vendor.f7abdec63796a339d922bf4e7590325e.js:2:927270)
    at Qa (vendor.f7abdec63796a339d922bf4e7590325e.js:2:927052)
    at nc (vendor.f7abdec63796a339d922bf4e7590325e.js:2:971434)
    at Ic (vendor.f7abdec63796a339d922bf4e7590325e.js:2:955158)
    at qc (vendor.f7abdec63796a339d922bf4e7590325e.js:2:954980)
    at Wc (vendor.f7abdec63796a339d922bf4e7590325e.js:2:954813)
    at zc (vendor.f7abdec63796a339d922bf4e7590325e.js:2:951646)
    at vendor.f7abdec63796a339d922bf4e7590325e.js:2:900396
    at t.unstable_runWithPriority (vendor.f7abdec63796a339d922bf4e7590325e.js:2:1395222)
    at Ki (vendor.f7abdec63796a339d922bf4e7590325e.js:2:900173)
    at Zi (vendor.f7abdec63796a339d922bf4e7590325e.js:2:900341)
    at $i (vendor.f7abdec63796a339d922bf4e7590325e.js:2:900276)
    at Lc (vendor.f7abdec63796a339d922bf4e7590325e.js:2:948977)
    at Object.enqueueSetState (vendor.f7abdec63796a339d922bf4e7590325e.js:2:904250)
    at km._.setState (vendor.f7abdec63796a339d922bf4e7590325e.js:2:1297296)
    at ogs.5.1-4075-g87407d2b-8c5b6ad03f2844c9c4785ce85007af68.js:2:782554
o589780.ingest.sentry.io/api/5750726/store/?sentry_key=f8e3b8de571e412b98ff8f98e12c7f58&sentry_version=7:1          
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by benjaminpjones** [comment]
As I suspected, `rounds` and `players` are the culprits...

If you look at `rounds` (https://online-go.com/api/v1/tournaments/85113/rounds), players 371 and 527014 are present.  But if you look at `players` (https://online-go.com/termination-api/tournament/85113/players), they aren't.

Why this is the case.. I do not know :)
